services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: fiap_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - tech-challenge-database-pgdata:/var/lib/postgresql/data
      - ./db-config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tech-challenge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/users
      DB_USERNAME: fiap_user
      DB_PASSWORD: 123456
      JWT_KEY: 4e5f8a9c2d1b7f6a3c8e9d0f1a2b3c4d5e6f7a8b9c0d1e2f
    ports:
      - "8080:8080"
    networks:
      - tech-challenge-network
    depends_on:
      postgres:
        condition: service_healthy


networks:
  tech-challenge-network:

volumes:
  tech-challenge-database-pgdata: