server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/users}
    username: ${DB_USERNAME:fiap_user}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app;
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: app
        format_sql: true
    show-sql: false

jwt:
  expiration: ${JWT_EXPIRATION:2592000000} # 30 dias
  key: ${JWT_KEY:4e5f8a9c2d1b7f6a3c8e9d0f1a2b3c4d5e6f7a8b9c0d1e2f}